files:
  include: 'src/**/*.s+(a|c)ss'
rules:
  no-empty-rulesets: 0
  property-sort-order: 0
  space-before-colon: 0
  class-name-format: 0
  force-pseudo-nesting: 0
  no-vendor-prefixes:
  - 1
  -
    excluded-identifiers:
      - 'webkit'
      - 'moz'
