playground:
  build: .
  ports:
    - 3000:3000
    - 3001:3001
    - 3002:3002
  volumes:
    - .:/home/app:rw
  environment:
    - NODE_ENV=production
  command: sh -c 'echo $NODE_ENV && npm run start'
